# Generated by Django 6.0.1 on 2026-01-11 10:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapsuleStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Дата для агрегации статистики",
                        unique=True,
                        verbose_name="Дата",
                    ),
                ),
                (
                    "total_created",
                    models.IntegerField(default=0, verbose_name="Всего создано"),
                ),
                (
                    "total_sent",
                    models.IntegerField(default=0, verbose_name="Всего отправлено"),
                ),
                (
                    "total_failed",
                    models.IntegerField(default=0, verbose_name="Всего ошибок"),
                ),
                (
                    "total_pending",
                    models.IntegerField(default=0, verbose_name="В ожидании"),
                ),
                (
                    "avg_delivery_time",
                    models.FloatField(
                        default=0, verbose_name="Среднее время доставки (часы)"
                    ),
                ),
                (
                    "max_delivery_time",
                    models.FloatField(
                        default=0, verbose_name="Максимальное время доставки (часы)"
                    ),
                ),
                (
                    "unique_recipients",
                    models.IntegerField(
                        default=0, verbose_name="Уникальных получателей"
                    ),
                ),
                (
                    "top_domains",
                    models.JSONField(
                        default=list,
                        help_text="Топ-10 доменов получателей",
                        verbose_name="Топ доменов",
                    ),
                ),
                (
                    "countries",
                    models.JSONField(
                        default=dict,
                        help_text="Количество капсул по странам",
                        verbose_name="Распределение по странам",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика капсул",
                "verbose_name_plural": "Статистика капсул",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EncryptionKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_id",
                    models.CharField(
                        help_text="Уникальный идентификатор ключа",
                        max_length=50,
                        unique=True,
                        verbose_name="ID ключа",
                    ),
                ),
                (
                    "key",
                    models.TextField(
                        help_text="Fernet ключ в base64", verbose_name="Ключ шифрования"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата истечения срока действия ключа",
                        null=True,
                        verbose_name="Истекает",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Используется ли ключ для шифрования",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Текущий ключ для шифрования",
                        verbose_name="Текущий",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество использований"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ключ шифрования",
                "verbose_name_plural": "Ключи шифрования",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RealTimeMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Ключ метрики"
                    ),
                ),
                (
                    "metric_value",
                    models.JSONField(default=dict, verbose_name="Значение метрики"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Истекает"
                    ),
                ),
            ],
            options={
                "verbose_name": "Метрика в реальном времени",
                "verbose_name_plural": "Метрики в реальном времени",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Включена ли двухфакторная аутентификация",
                        verbose_name="2FA включена",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Для SMS аутентификации",
                        max_length=20,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Последний IP входа"
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(
                        default=0, verbose_name="Неудачные попытки входа"
                    ),
                ),
                (
                    "account_locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Аккаунт заблокирован до"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Группы, к которым принадлежит пользователь",
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.group",
                        verbose_name="Группы",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Конкретные права для этого пользователя",
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.permission",
                        verbose_name="Права пользователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название шаблона"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Используйте {{имя}} для подстановки значений",
                        verbose_name="Содержание шаблона",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("personal", "Личное"),
                            ("business", "Деловое"),
                            ("holiday", "Праздничное"),
                            ("reminder", "Напоминание"),
                            ("custom", "Пользовательский"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=list,
                        help_text="Список переменных для подстановки",
                        verbose_name="Переменные",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Доступен всем пользователям",
                        verbose_name="Публичный шаблон",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество использований"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон сообщения",
                "verbose_name_plural": "Шаблоны сообщений",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeCapsule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="Email получателя"),
                ),
                (
                    "encrypted_message",
                    models.TextField(verbose_name="Зашифрованное сообщение"),
                ),
                ("scheduled_date", models.DateTimeField(verbose_name="Дата отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает отправки"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка"),
                            ("processing", "В процессе отправки"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="Причина ошибки"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capsules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Капсула времени",
                "verbose_name_plural": "Капсулы времени",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CapsuleAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to="attachments/%Y/%m/%d/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Имя файла"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="Размер файла"),
                ),
                (
                    "file_type",
                    models.CharField(max_length=100, verbose_name="Тип файла"),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=True, verbose_name="Зашифрован"),
                ),
                (
                    "encryption_key_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID ключа шифрования",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "capsule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.timecapsule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение",
                "verbose_name_plural": "Вложения",
            },
        ),
    ]
